import type { PlanetConfig } from "./solarSystemObjects";

export const planetConfigs: PlanetConfig[] = [
    {
        name: "mercury",
        size: 0.12,
        distance: 1.1,
        color: "#a6a6a6",
        orbitSpeed: 0.025,
        rotationSpeed: 0.02,
        startAngle: 0.2,
    },
    {
        name: "venus",
        size: 0.2,
        distance: 1.6,
        color: "#d8b26e",
        orbitSpeed: 0.018,
        rotationSpeed: 0.012,
        startAngle: 1.1,
    },
    {
        name: "earth",
        size: 0.22,
        distance: 2.1,
        color: "#3b82f6",
        orbitSpeed: 0.014,
        rotationSpeed: 0.03,
        startAngle: 2.4,
    },
    {
        name: "mars",
        size: 0.18,
        distance: 2.7,
        color: "#d97745",
        orbitSpeed: 0.011,
        rotationSpeed: 0.025,
        startAngle: 3.0,
    },
    {
        name: "jupiter",
        size: 0.45,
        distance: 3.6,
        color: "#d6a36a",
        orbitSpeed: 0.007,
        rotationSpeed: 0.04,
        startAngle: 4.2,
    },
    {
        name: "saturn",
        size: 0.38,
        distance: 4.6,
        color: "#e5c77f",
        orbitSpeed: 0.005,
        rotationSpeed: 0.035,
        startAngle: 5.1,
    },
    {
        name: "uranus",
        size: 0.3,
        distance: 5.5,
        color: "#7dd3fc",
        orbitSpeed: 0.0035,
        rotationSpeed: 0.025,
        startAngle: 5.8,
    },
    {
        name: "neptune",
        size: 0.3,
        distance: 6.3,
        color: "#2563eb",
        orbitSpeed: 0.0028,
        rotationSpeed: 0.022,
        startAngle: 0.9,
    },
] as const;